### ISSUE TITLE
Cannot read property 'helperFunction' of undefined

### ISSUE THREAD

**Issue by jcope2013** [nibynic/ember-form-builder#1]
on ember 1.13.2, what is the latest this library supports?

```
Cannot read property 'helperFunction' of undefined
```

https://github.com/nibynic/ember-simple-form/blob/master/addon/helpers/input-on.js#L18

most likely has to do with the new helper API in 1.13

http://emberjs.com/blog/2015/06/12/ember-1-13-0-released.html
https://github.com/emberjs/rfcs/blob/master/text/0053-helpers.md
https://github.com/emberjs/rfcs/pull/58

**Comment by piotrekbator** [comment]
Unfortunately, we haven't yet tested the library with anything above Ember 1.12. 

I hope to find some time to fix this next week. And maybe that'd be a good time to tidy up some things and finally release it to npm :)

**Comment by piotrekbator** [comment]
It was a little tricky to fix, but the library should now work fine with Ember 1.13.2.
