### ISSUE TITLE
Ember validations delay

### ISSUE THREAD

**Issue by cimtico** [nibynic/ember-form-builder#2]
How can I get ember validation errors to display until after the user has interacted with the input field?

**Comment by piotrekbator** [comment]
Sorry, for the late response.

The errors should work that way already: they are only displayed if either user has focused out of an input or the model you're working on was already marked as invalid (isValid set to false) when you first displayed the form.
The second case is used for scenarios when you redirect the user to a form that needs to be corrected.

So, please, check your model's isValid flag when displaying the form (transitioning to route, rendering component, whatever). If it's true and you still get all the error messages displayed - could you pleas provide a code sample that demonstrates the problem?

And also - make sure that you have the newest version installed (still from git).
