### ISSUE TITLE
Thoughts on supporting contextual components?

### ISSUE THREAD

**Issue by ivanvanderbyl** [nibynic/ember-form-builder#4]
I've really been enjoying this library, but I was wondering what you're thoughts are on supporting contextual components?

``` hbs
{{#form-builder for=this action="submit" as |f|}}

  {{f.input "title"}}
  {{f.input "category" collection=categories
             optionValuePath="content.id" optionLabelPath="content.fullName"}}
  {{f.input "isPublished"}}
  {{f.input "publishedOn" as="date"}}
  {{f.input "price" unit="PLN" hint="Leave empty if this is a free article"}}

  {{f.submit "Save"}}

{{/form-builder}}
```

**Comment by piotrekbator** [comment]
Thanks! 

We certainly are planning on moving to contextual components. The current API  originates from Ember 1.12 and we've only fully upgraded to Ember 2.x last week.

Unfortunately I have no idea when I will be able to take care of this. Hopefully within the next two weeks.

**Comment by piotrekbator** [comment]
@ivanvanderbyl Done :)
