### ISSUE TITLE
Validation errors displayed as [object Object]

### ISSUE THREAD

**Issue by masterchef** [nibynic/ember-form-builder#43]
I found that my model field validations coming from server side as JSON API errors are rendering as `[object Object]` so I had to extend the default wrapper and overwrite:
```
{{#each @config.validations.errors as |error i|~}}
  {{if i ", "}}{{error.message}}
{{~/each}
```

https://github.com/nibynic/ember-form-builder/blob/0cab6ca9cc24212f9d37214c67f451befd235704/addon/components/input-wrappers/default.hbs#L17

**Comment by jembezmamy** [comment]
Hey, sorry for the late response 🙈.

Do you use any validation addon? In Ember CP Validations you can use [ds-error](http://adopted-ember-addons.github.io/ember-cp-validations/docs/classes/DS%20Error.html) to unwrap these messages. Then it should work fine.

**Comment by masterchef** [comment]
I'm not using Ember CP validations as it's not octane compatible. My workaround with a custom wrapper worked fine.
