### ISSUE TITLE
Support for Ember-intl

### ISSUE THREAD

**Issue by srsgores** [nibynic/ember-form-builder#5]
Looks very similar to `ember-i18n`, so it might be a quick fix.  Will look into integration.

**Comment by piotrekbator** [comment]
Well, it seems that ember-intl is quite popular, judging by npm downloads almost as popular as ember-18n. Having support for this library in our our form builder is a good idea, but I don't think we'll have time to implement it soon.

Would you consider making a PR introducing support for ember-intl? I imagine that we should create an internal internationalization service that'll encapsulate translations within ember-form-builder and delegate them to one of the supported internationalization plugins. If you could write this, we'll merge it ASAP.

**Comment by srsgores** [comment]
Yeah, already got integration working last night.  Will submit pr in the couple days.

**Comment by piotrekbator** [comment]
Awesome!

**Comment by srsgores** [comment]
Just working on this now, and there is the question of how to deal with the scenario when **both** `i18n` **and** `ember-intl` are available.  I am just defaulting to `ember-intl`, but maybe we should throw a warning?

**Comment by piotrekbator** [comment]
I don't think this is a very common scenario, but probably we could expose a configuration setting that allows users to specify which library they wish to use, WDYT? But probably defaulting to one of the libraries is fine for now, but it should be `ember-i18n` not `ember-intl` -- to maintain backward compatibility.

**Comment by srsgores** [comment]
[PR is made](https://github.com/nibynic/ember-form-builder/pull/6).  Let me know your thoughts.  Wasn't sure what `translation` was, so I had to rename the service to `translationService`.  The names seem awfully redundant to me, and I think this needs work.

**Comment by piotrekbator** [comment]
@srsgores could you give me write access to your fork? I could try fixing the errors that occur i travis on your branch.

**Comment by srsgores** [comment]
Sent.  I thought I'd found the issue with the tests failing, but it seems bigger than that now; [the Travis tests indicate that the service isn't being found](https://travis-ci.org/nibynic/ember-form-builder/jobs/188435362#L732):

> Promise rejected before Defaults to ember-i18n when both i18n and ember-intl are present: Attempting to register an unknown factory: `service:translation`

I do find this particularly strange, [since the `translation` service is being exported at `app/services`](https://github.com/srsgores/ember-form-builder/blob/master/app/services/translation.js).  But hopefully now that I've added it, some more tests should pass.

**Comment by piotrekbator** [comment]
Thanks. I'll try looking into it tomorrow.
