### ISSUE TITLE
addon not working

### ISSUE THREAD

**Issue by magickrc** [nibynic/ember-form-builder#65]
when I added simple example form with one input I getting error, but  nothing found mentioning about some additional settings
what I do wrong?

my ember version 4.12
"ember-form-builder": "^3.0.0-beta.2",

![image](https://github.com/nibynic/ember-form-builder/assets/5837987/38d904ba-176c-418d-ad37-96598692b0b0)

**Comment by jembezmamy** [comment]
Hello @magickrc! Sorry for a late response, I was on a vacation. As the error message says, you have to register your inputs and wrappers to make them work with Embroider. Running `ember install ember-form-builder` should solve the issue.
