### ISSUE TITLE
Support for success message

### ISSUE THREAD

**Issue by cimtico** [nibynic/ember-form-builder#7]
The integration with ember validations and displaying error messages is great. However, would it be possible to have a similar behavior for success messages? 
Use cases would vary from valid email checks, available usernames, etc. This would be a great way to provide feedback to the user when the field's value is valid.
It could work in a similar manner as errors, just with a different key (maybe successMessages or something of the sort instead of errors?) and a different css class.

**Comment by dmatamoroscr** [comment]
Or maybe some sort of generic message field with a custom css class to be passed for other cases such as warnings

**Comment by piotrekbator** [comment]
Thanks :)

First of all, this should be very easy to implement on your own in your own project - at least to just test it out. You'd need to extend `SimpleInput` component and add a new computed property similar to `hasErrors`. Something like this:

``` javascript
isSuccessful: Ember.computed("hasFocusedOut", "builder.isValid", "errors", function() {
    return this.get("hasFocusedOut") && this.get("builder.isValid") && Ember.isEmpty(this.get("errors"));
  }),
```

Then you could copy the `SimpleInput`'s template to your app and add there a few lines that display whatever you want (a message, an icon, whatever) based on `isSuccessful`.

Could you try this out and get back to me with feedback if it really was this simple?

If so - I'm not sure if this is a feature we should include in the library. Maybe it is - I'm just not sure if it's common enough and I can't think of an elegant solution that wouldn't force it on every user.

@avdmatamoros we do support warning messages but only through our fork of `ember-validations` which never got merged: https://github.com/nibynic/ember-validations
