### ISSUE TITLE
Which Ember Validations Package?

### ISSUE THREAD

**Issue by srsgores** [nibynic/ember-form-builder#8]
[There are many "Ember Validations" packages](https://www.emberaddons.com/?query=validation).  Which one is to be used with this addon?

**Comment by piotrekbator** [comment]
@srsgores The DockYard's one: https://github.com/DockYard/ember-validations. It's no longer actively developed but it is maintained by them. I've added a link to the Readme.

But still Ember Form Builder whould work well with many other libraries. As far as I remember, we only need a validate() method returning a promise to automatically invoke validation on form submit. Errors format is a standard for ember-data. Should be fine with almost any other validation addon.
